blank_issues_enabled: false
contact_links:
  - name: Ideas
    url: https://github.com/PencilNavigator/freenom-workers/discussions/new?category=ideas
    about: Any ideas for this project.
  - name: Support
    url: https://github.com/PencilNavigator/freenom-workers/discussions/new?category=support
    about: nswers to questions and support is provided on the discussions page.
  - name: General Discussions
    url: https://github.com/PencilNavigator/freenom-workers/discussions/categories/general
    about: Discuss project related topics on the discussions page.
