blank_issues_enabled: false
contact_links:
  - name: 想法/功能请求 Idea/Feature Request
    url: https://github.com/PencilNavigator/freenom-workers/discussions/new?category=feature-request
    about: 请前往Discussions提交你的想法或功能请求。 Idea，Feature Request is handled on Discussions.
  - name: 帮助支持 Support
    url: https://github.com/PencilNavigator/freenom-workers/discussions/new?category=support
    about: 提问，求助，以及其他类型的帮助支持，请前往Discussions。 Answers to questions and support is provided on the discussions page.
  - name: 交流 General Discussions
    url: https://github.com/PencilNavigator/freenom-workers/discussions/categories/general
    about: 和他人交流项目有关的内容。 Discuss project related topics on the discussions page.
